@server = http://localhost:8000

###
GET {{server}}

###
GET {{server}}/register

###
GET {{server}}/login

###
GET {{server}}/users

### 회원가입 요청
POST {{server}}/user/register
Content-Type: application/json; charset=UTF-8

{
  "id":null,
  "user_id": "mos",
  "password": "1234",
  "user_name": "moss"
}

### 로그인 요청
POST {{server}}/login
Content-Type: application/json; charset=UTF-8

{
  "user_id": "cosmos",
  "password": "1234"
}

