@server = http://localhost:8000

###
GET {{server}}

###
GET {{server}}/register

###
GET {{server}}/login

###
GET {{server}}/users

### 회원가입 요청
POST {{server}}/api/user/register
Content-Type: application/json; charset=UTF-8

{
  "id":null,
  "user_id": "qwerty",
  "password": "1234",
  "user_name": "speed",
  "is_admin" : "null"
}

### 로그인 요청
POST {{server}}/api/user/login
Content-Type: application/json; charset=UTF-8

{
  "user_id": "orange",
  "password": "1234"
}

